[workspace]
resolver = "3"
members = [
    "crates/lowess",
    "crates/fastLowess",
    "bindings/python",
    "bindings/r/src",
]
exclude = ["bindings/r/src/vendor"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
