[package]
name = "rfastlowess"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = "1.89.0"

# Metadata
description = "High-level, fast LOWESS smoothing built on top of the fastLowess Rust crate."
readme = "README.md"

# Links
repository = "https://github.com/thisisamirv/rfastlowess"
homepage = "https://github.com/thisisamirv/rfastlowess"

# Categories
keywords = { workspace = true }
categories = { workspace = true }

include = ["Cargo.toml", "lib.rs", "vendor/**/*", "README.md", "LICENSE"]

# Build
[dependencies]
fastLowess = { workspace = true, features = ["dev"] }
extendr-api = { workspace = true }

[lib]
name = "rfastlowess"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[features]
default = []
dev = []

[profile.release]
opt-level = 3
lto = false
codegen-units = 1

# Document all features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
