[package]
name = "rfastlowess"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

# Metadata
description = { workspace = true }
readme = { workspace = true }

# Links
repository = { workspace = true }
homepage = { workspace = true }

# Categories
keywords = { workspace = true }
categories = { workspace = true }

include = ["Cargo.toml", "lib.rs", "vendor/**/*", "README.md", "LICENSE"]

# Build
[dependencies]
fastLowess = { workspace = true, features = ["dev"] }
extendr-api = { workspace = true }

[lib]
name = "rfastlowess"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]

[features]
default = []
dev = []

[profile.release]
opt-level = 3
lto = false
codegen-units = 1

# Document all features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
