[package]
name = "fastLowess-py"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
publish = false

[dependencies]
fastLowess = { workspace = true, features = ["dev", "cpu"] }
pyo3 = { workspace = true }
numpy = { workspace = true }

[lib]
name = "fastlowess"
crate-type = ["cdylib"]

[features]
default = []
dev = []
