[package]
name = "fastLowess-py"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

# Metadata
description = "High-level, fast LOWESS smoothing built on top of the fastLowess Rust crate."
readme = "README.md"

# Links
repository = "https://github.com/thisisamirv/fastLowess-py"
homepage = "https://github.com/thisisamirv/fastLowess-py"

# Categories
keywords = { workspace = true }
categories = { workspace = true }

include = [
    "src/**/*",
    "docs/**/*.svg",
    "fastlowess/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
    "CHANGELOG.md",
]

# Build
[dependencies]
fastLowess = { workspace = true, features = ["dev", "cpu"] }
pyo3 = { workspace = true }
numpy = { workspace = true }

[lib]
name = "fastlowess"
crate-type = ["cdylib"]

[features]
default = []
dev = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

# Document all features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
