name: pkgcheck

# Cancel any running job if a new push is made
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["R-CMD-check"]
    types:
      - completed
    branches:
      - main

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install pkgcheck
        run: |
          install.packages(c("pkgcheck", "pkgstats"), repos = c("https://ropensci.r-universe.dev", "https://cloud.r-project.org"))
        shell: Rscript {0}

      - name: Run pkgcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          library(pkgcheck)
          library(pkgstats)
          check <- pkgcheck::pkgcheck("bindings/r")
          print(check)
          # Fail if checks don't pass
          if (any(check$checks$error)) stop("pkgcheck failed with errors")
        shell: Rscript {0}
