name: SRR-check

# Cancel any running job if a new push is made
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["R-CMD-check"]
    types:
      - completed
    branches:
      - main

jobs:
  SRR-check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "BiocManager", "covr"))
          install.packages(c("pkgcheck", "pkgstats", "toml", "visNetwork"), repos = c("https://ropensci.r-universe.dev", "https://cloud.r-project.org"))
          # Install package dependencies including suggests (needed for BiocStyle vignette)
          remotes::install_deps("bindings/r", dependencies = TRUE, repos = c(BiocManager::repositories(), "https://cloud.r-project.org"))
        shell: Rscript {0}

      - name: Debug Coverage
        run: |
          tryCatch({
            print(covr::package_coverage("bindings/r"))
          }, error = function(e) {
            print(e)
            message("Covr failed to run directly")
          })
        shell: Rscript {0}

      - name: Run pkgcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          library(pkgcheck)
          library(pkgstats)
          check <- pkgcheck::pkgcheck("bindings/r")
          print(check)
          # Fail if checks don't pass
          if (any(check$checks$error)) stop("pkgcheck failed with errors")
        shell: Rscript {0}
