[package]
name = "fastLowess"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

# Metadata
description = { workspace = true }
readme = "README.md"

# Links
repository = { workspace = true }
documentation = "https://lowess.readthedocs.io/"
homepage = { workspace = true }

# Categories
keywords = { workspace = true }
categories = { workspace = true }

# Build
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[dependencies]
lowess = { workspace = true, features = ["dev"] }
num-traits = { workspace = true, features = ["libm"] }
ndarray = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
futures-intrusive = { workspace = true, optional = true }

[dev-dependencies]
approx = { workspace = true }

[features]
default = ["cpu"]
cpu = ["dep:rayon", "dep:ndarray"]
gpu = ["dep:wgpu", "dep:bytemuck", "dep:pollster", "dep:futures-intrusive"]
dev = []

# Document all features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
