[package]
name = "fastLowess"
version = "0.4.0"
edition = "2024"
rust-version = "1.85.0"

# Metadata
description = "High-level, parallel LOWESS smoothing built on top of the lowess crate, with ndarray integration and rayon-based parallelism."
authors = ["Amir Valizadeh <thisisamirv@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

# Links
repository = "https://github.com/thisisamirv/fastLowess"
documentation = "https://docs.rs/fastLowess"
homepage = "https://github.com/thisisamirv/fastLowess"

# Categories
keywords = ["lowess", "smoothing", "statistics", "regression", "bioinformatics"]
categories = ["science", "algorithms"]

# Build
include = [
    "src/**/*",
    "docs/**/*.svg",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
    "CHANGELOG.md",
]

[dependencies]
lowess = { version = "0.7", features = ["dev"] }
num-traits = { version = "0.2.19", default-features = false, features = [
    "libm",
] }
ndarray = { version = "0.17.1", default-features = false, optional = true }
rayon = { version = "1.11.0", optional = true }
wgpu = { version = "28.0.0", optional = true }
bytemuck = { version = "1.24.0", features = ["derive"], optional = true }
pollster = { version = "0.4.0", optional = true }
futures-intrusive = { version = "0.5.0", optional = true }

[dev-dependencies]
approx = "0.5.1"

[features]
default = ["cpu"]
cpu = ["dep:rayon", "dep:ndarray"]
gpu = ["dep:wgpu", "dep:bytemuck", "dep:pollster", "dep:futures-intrusive"]
dev = []

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

# Document all features
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
